name: deploy to malariaone server
on: create
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout latest repo version
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        timeout: 30m
        command_timeout: 60m
        script: |
          cd /home/sepmein/malaria-one
          git fetch --all
          git reset --hard origin/master
          export NODE_OPTIONS='--max-old-space-size=8192'
          gatsby clean
          gatsby build
          rm -rf /var/www/html/*
          mv -v public/* /var/www/html/
