name: deploy to malariaone server
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout latest repo version
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: "165.227.174.250"
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/sepmein/malaria-one
          git pull origin master
          
